services:
  xampp:
    image: tomsik68/xampp:latest
    container_name: uc-server-2
    privileged: true
    ports:
      - "8088:80"
    volumes:
      - /workspaces/UniConnect:/opt/lampp/htdocs/uniconn:Z  ## รันบน GithubWorkspace
      # - ~/Documents/uniconn:/opt/lampp/htdocs/uniconn:Z  ## รันบน Local Machine
    restart: unless-stopped
